### ISSUE TITLE
 Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.

### ISSUE THREAD

**Issue by hitmacreed** [opdahlmann/ng2-opd-popup-sample#23]
Getting this error `ERROR in node_modules/ng2-opd-popup/node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
`

**Comment by abdelrahmanlifestyle** [comment]
same issue here

**Comment by asherbig** [comment]
Also got this issue

**Comment by petrovserg** [comment]
Go to component's folder (e.g. you-project\node_module\ng2-opd-popup\) and delete node_modules sub folder.

**Comment by oscarrodar** [comment]
@petrovserg is messing around 😆
